### ISSUE TITLE
Missing lib express-error-handler

### ISSUE THREAD

**Issue by tychris** [ludovic-gonthier/snowshoe#10]
Lors de l'installation du projet , il y a une erreur.

<pre>
module.js:338
    throw err;
          ^
Error: Cannot find module 'express-error-handler'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/patisson/lemonde/snowshoe/app.js:37:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

</pre>

**Comment by ludovic-gonthier** [comment]
Fixed at 44cfad106f5b593bc20942ac660371455a88db4f
