### ISSUE TITLE
Loss of connection

### ISSUE THREAD

**Issue by ludovic-gonthier** [ludovic-gonthier/snowshoe#33]
## Description

Snowshoe seems to loss the connection and then calls the github API anonymously causing Github to return 403 thus disabling the user ability to connect to the application.

The URL's cache seems to blame. The closed PR URL's aren't purged, growing the DB size out of control.
## Actions

Purge DB from unnecessary data.
Reduce the size of stored JSON
## Trace

```
GET /auth/github/callback?code=37dacc02936c8b00ca9b - - ms - -
failed to fetch user profile (status: 403 data: {"message":"API rate limit exceeded for 194.3.81.110. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"})
    at /opt/web/snowshoe/node_modules/passport-github/lib/passport-github/strategy.js:90:28
    at passBackControl (/opt/web/snowshoe/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/opt/web/snowshoe/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:142:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by ludovic-gonthier** [comment]
For those running in the problem:
- Stop the application.
- Run  `gulp` (will reset the db)

That solves the problem (temporarly).
