### ISSUE TITLE
Error at launch - size DB

### ISSUE THREAD

**Issue by bdronneau** [ludovic-gonthier/snowshoe#37]
# Description

After some week with snowshoe have got an error :

``` js
undefined:0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/srv/snowshoe/lib/github/request.js:43:29)
    at Request.self.callback (/srv/snowshoe/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/srv/snowshoe/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/srv/snowshoe/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

and when I'm restarting (`gulp server`)

``` js
[10:49:19] Using gulpfile /srv/snowshoe/gulpfile.js
[10:49:19] Starting 'server'...
[10:49:19] Finished 'server' after 23 ms
livereload[tiny-lr] listening on 35729 ...
================================================================================
Server launched.

Informations:
        Hostname: X.X.X.X
        Port: 3000

================================================================================
/srv/snowshoe/node_modules/nedb/lib/datastore.js:67
    if (err) { throw err; }
                     ^
RangeError: File size is greater than possible Buffer: 0x3FFFFFFF bytes
    at fs.js:282:19
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Size of `etags.db`

``` bash
2.9G    cache/etags.db
```

I solve my issue by delete the db
# Actions
- Cron for clean db ?

**Comment by ludovic-gonthier** [comment]
I ran into the probleme with an older version on SnowShoe. Can you give me the SHA-1 corresponding to the master HEAD you're using.
Try to fetch the last version of the master, the DB size shouldn't grow that much anymore.

**Comment by bdronneau** [comment]
``` bash
commit d956c2ed4d903b14e8cb148a11eddedab5f89b3b
Merge: 1041286 71f907b
Author: Ludovic Gonthier <gonthier@lemonde.fr>
Date:   Mon Jul 27 11:55:59 2015 +0200

    Merge branch 'empty-body'
```

Maybe it's too old and already fix

EDIT : I'll test with the last version

**Comment by ludovic-gonthier** [comment]
Yep, the problem is solved in https://github.com/ludovic-gonthier/snowshoe/commit/937e2717fdc519768b04311d6cd25cd9a81c3436

**Comment by bdronneau** [comment]
With the latest version :

``` bash
commit e5a4984bb9b66851363c883fd008017f6c5f6e99
Merge: 0f12163 ca06cf6
Author: Ludovic Gonthier <gonthier@lemonde.fr>
Date:   Fri Sep 11 18:11:22 2015 +0200

    Merge branch 'polling-concurrency'
```

output :

``` bash
[11:17:04] Using gulpfile /srv/snowshoe/gulpfile.js
[11:17:04] Starting 'server'...
[11:17:04] Finished 'server' after 23 ms
livereload[tiny-lr] listening on 35729 ...
================================================================================
Server launched.

Informations:
        Hostname: X.X.X.X
        Port: 3000

================================================================================
/srv/snowshoe/node_modules/nedb/lib/datastore.js:67
    if (err) { throw err; }
                     ^
RangeError: File size is greater than possible Buffer: 0x3FFFFFFF bytes
    at fs.js:282:19
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by bdronneau** [comment]
maybe it's not working because my DB his already too big

**Comment by ludovic-gonthier** [comment]
Try to run `npm install`. I do not have the problem

**Comment by bdronneau** [comment]
Already done for the `npm install` (for installing gulp-mocha)

**Comment by ludovic-gonthier** [comment]
Try to remove the cache, to see if the errors still occurs

**Comment by ludovic-gonthier** [comment]
The DB file must be corrupted

**Comment by bdronneau** [comment]
:+1:

**Comment by bdronneau** [comment]
It's good with new DB, I'll keep an eye on DB size

**Comment by ludovic-gonthier** [comment]
Here, with 30 users, running for 1 months the DB size is 617K

**Comment by bdronneau** [comment]
I'll wait a long time only 6 here :)

**Comment by ludovic-gonthier** [comment]
Indeed
